import { Inter } from 'next/font/google'
import Link from 'next/link'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ko">
      <body className={inter.className}>
        <header className="fixed left-0 right-0 top-0 z-50 p-2 text-center">
          <h1 className="mt-8 text-4xl font-bold text-white">
            <Link href="/">동현dev</Link>
          </h1>
          <nav className="border-b-10 mb-8 border-black p-3 text-center">
            <ul className="flex justify-center space-x-8 text-lg">
              <li>
                <Link href="/portfolio">portfolio</Link>
              </li>
              <li>
                <Link href="/development">dev</Link>
              </li>
              <li>
                <Link href="/life">life</Link>
              </li>
            </ul>
          </nav>
        </header>
        {children}
      </body>
    </html>
  )
}
