export default async function Home() {
  return (
    <main className="h-full w-screen flex-col items-center justify-center">
      <div>top</div>
      <div>hihi</div>
      <div>hihi</div>
      <div>hihi</div>
      <div>hihi</div>
      <div>hihi</div>
      <div>hihi</div>
      <div>hihi</div>
      <div>hihi</div>
      <div>hihi</div>
      <div>hihi</div>
      <div>hihi</div>
      <div>hihi</div>
      <div>hihi</div>
      <div>hihi</div>
      <div>hihi</div>
      <div>hihi</div>
      <div>hihi</div>
      <div>hihi</div>
      <div>hihi</div>
      <div>hihi</div>
      <div>hihi</div>
      <div>hihi</div>
      <div>hihi</div>
      <div>hihi</div>
      <div>hihi</div>
      <div>hihi</div>
      <div>hihi</div>
      <div>hihi</div>
      <div>hihi</div>
      <div>hihi</div>
      <div>hihi</div>
      <div>hihi</div>
      <div>hihi</div>
      <div>hihi</div>
      <div>hihi</div>
      <div>hihi</div>
      <div>hihi</div>
      <div>hihi</div>
      <div>hihi</div>
      <div>hihi</div>
      <div>hihi</div>
      <div>hihi</div>
      <div>hihi</div>
      <div>hihi</div>
      <div>hihi</div>
      <div>hihi</div>
      <div>hihi</div>
      <div>hihi</div>
      <div>hihi</div>
      <div>hihi</div>
      <div>hihi</div>
      <div>bottom</div>
    </main>
  )
}
